package com.domainify.entity;

public enum NotificationType {
    TICKET_CREATED,
    TICKET_CUSTOMER_REPLY,
    TICKET_STAFF_REPLY,
    TICKET_MENTION,
    TICKET_STATUS_CHANGED,
    TICKET_ASSIGNED,
    TICKET_UNASSIGNED,
    TICKET_CLOSED,
    TICKET_REOPENED
}
